const skinInput = document.getElementById("skinInput");
const loading = document.getElementById("loading");
const preview = document.getElementById("preview");
const ctx = preview.getContext("2d");
const downloadBtn = document.getElementById("downloadBtn");

let generatedImage = null;

skinInput.addEventListener("change",(e)=>{

    const file = e.target.files[0];
    if(!file) return;

    loading.classList.remove("hidden");

    setTimeout(()=>{

        const img = new Image();

        img.onload = ()=>{

            ctx.clearRect(0,0,128,128);

            // Skin face crop
            ctx.drawImage(
                img,
                8,8,8,8,
                32,32,64,64
            );

            generatedImage = preview.toDataURL();

            loading.classList.add("hidden");
            downloadBtn.classList.remove("hidden");
        };

        img.src = URL.createObjectURL(file);

    },5000);
});

downloadBtn.addEventListener("click",async()=>{

    const zip = new JSZip();

    const base64 = generatedImage.split(",")[1];

    zip.file(
        "textures/items/totem.png",
        base64,
        {base64:true}
    );

    zip.file(
        "manifest.json",
        JSON.stringify({
            format_version:2,
            header:{
                name:"Shy Totem Pack",
                description:"Generated by SHY TOTEM EDITOR",
                uuid:crypto.randomUUID(),
                version:[1,0,0],
                min_engine_version:[1,20,0]
            },
            modules:[{
                type:"resources",
                uuid:crypto.randomUUID(),
                version:[1,0,0]
            }]
        },null,2)
    );

    const blob = await zip.generateAsync({
        type:"blob"
    });

    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "ShyTotem.mcpack";
    a.click();
});
